last_change = 2026-06-27T20:52:06.452748Z
addr = 0x15afa0
size = 0x4a2
name = "BATTLE_CObjectManager::CountDownWorldStop"

[header]
name = "BATTLE_CObjectManager::CountDownWorldStop"
addr = 0x15afa0

[header.args]
