last_change = 2026-06-27T20:52:06.453082Z
addr = 0x18e080
size = 0xb
name = "OBJ_CBase::AtkWallBoundStunTimeCounterHitReset"

[header]
name = "OBJ_CBase::AtkWallBoundStunTimeCounterHitReset"
addr = 0x18e080

[header.args]
