last_change = 2026-06-27T20:52:06.453299Z
addr = 0x18ef90
size = 0xb
name = "OBJ_CBase::AtkStaggerMinTimeCounterHitReset"

[header]
name = "OBJ_CBase::AtkStaggerMinTimeCounterHitReset"
addr = 0x18ef90

[header.args]
