last_change = 2026-06-27T20:52:06.453393Z
addr = 0x191980
size = 0x39
name = "OBJ_CBase::CreateParticleArgColorByPaletteIndex"

[header]
name = "OBJ_CBase::CreateParticleArgColorByPaletteIndex"
addr = 0x191980

[header.args]
