last_change = 2026-06-27T20:52:06.453390Z
addr = 0x191910
size = 0x3d
name = "OBJ_CBase::CreateParticleArgAngleRel"

[header]
name = "OBJ_CBase::CreateParticleArgAngleRel"
addr = 0x191910

[header.args]
