last_change = 2026-06-27T20:52:06.453876Z
addr = 0x1cf1c0
size = 0x1c
name = "OBJ_CBase::PlayerInitializeOnEasyReset"

[header]
name = "OBJ_CBase::PlayerInitializeOnEasyReset"
addr = 0x1cf1c0

[header.args]
