last_change = 2026-06-27T20:52:06.454112Z
addr = 0x392834
size = 0x2e
name = "?_W_Getmonths@_Locinfo@std@@QBEPBGXZ"

[header]
name = "?_W_Getmonths@_Locinfo@std@@QBEPBGXZ"
addr = 0x392834

[header.args]
