last_change = 2026-06-27T20:52:06.454693Z
addr = 0x3a6a1a
size = 0x39
name = "?_RegisterCallback@_CancellationTokenState@details@Concurrency@@QAEPAV_CancellationTokenRegistration@23@P6AXPAX@Z0H@Z"

[header]
name = "?_RegisterCallback@_CancellationTokenState@details@Concurrency@@QAEPAV_CancellationTokenRegistration@23@P6AXPAX@Z0H@Z"
addr = 0x3a6a1a

[header.args]
