last_change = 2026-06-27T20:52:06.455132Z
addr = 0x3bca7e
size = 0xae
name = "??1SchedulerBase@details@Concurrency@@UAE@XZ"

[header]
name = "??1SchedulerBase@details@Concurrency@@UAE@XZ"
addr = 0x3bca7e

[header.args]
