last_change = 2026-06-27T20:52:06.455062Z
addr = 0x3bb59b
size = 0x2e
name = "??1ContextBase@details@Concurrency@@UAE@XZ"

[header]
name = "??1ContextBase@details@Concurrency@@UAE@XZ"
addr = 0x3bb59b

[header.args]
