last_change = 2026-06-27T20:52:06.455103Z
addr = 0x3bbf6f
size = 0x1a
name = "?PushContextToTls@ContextBase@details@Concurrency@@AAEXPAV123@@Z"

[header]
name = "?PushContextToTls@ContextBase@details@Concurrency@@AAEXPAV123@@Z"
addr = 0x3bbf6f

[header.args]
