last_change = 2026-06-27T20:52:06.455078Z
addr = 0x3bb90a
size = 0xc7
name = "?CancelStealers@ContextBase@details@Concurrency@@QAEXPAV_TaskCollectionBase@23@@Z"

[header]
name = "?CancelStealers@ContextBase@details@Concurrency@@QAEXPAV_TaskCollectionBase@23@@Z"
addr = 0x3bb90a

[header.args]
