last_change = 2026-06-27T20:52:06.455671Z
addr = 0x3cafca
size = 0x28
name = "?_GetTokenState@_TaskCollectionBase@details@Concurrency@@QAEPAV_CancellationTokenState@23@PAPAV_CancellationTokenRegistration@23@@Z"

[header]
name = "?_GetTokenState@_TaskCollectionBase@details@Concurrency@@QAEPAV_CancellationTokenState@23@PAPAV_CancellationTokenRegistration@23@@Z"
addr = 0x3cafca

[header.args]
