last_change = 2026-06-27T20:52:06.455343Z
addr = 0x3c0439
size = 0x19
name = "?DesiredHWThreads@SchedulerProxy@details@Concurrency@@QBEIXZ"

[header]
name = "?DesiredHWThreads@SchedulerProxy@details@Concurrency@@QBEIXZ"
addr = 0x3c0439

[header.args]
