last_change = 2026-06-27T20:52:06.455345Z
addr = 0x3c0452
size = 0x3a
name = "?DestroyAllocatedNodeData@ResourceManager@details@Concurrency@@QAEXPAUSchedulerNode@23@@Z"

[header]
name = "?DestroyAllocatedNodeData@ResourceManager@details@Concurrency@@QAEXPAUSchedulerNode@23@@Z"
addr = 0x3c0452

[header.args]
