last_change = 2026-06-27T20:52:06.455722Z
addr = 0x3cbe87
size = 0x33
name = "?GetEnableFlags@Etw@details@Concurrency@@QAEK_K@Z"

[header]
name = "?GetEnableFlags@Etw@details@Concurrency@@QAEK_K@Z"
addr = 0x3cbe87

[header.args]
