last_change = 2026-06-27T20:52:06.455710Z
addr = 0x3cbb34
size = 0x34
name = "?_ReleaseAlias@_TaskCollection@details@Concurrency@@AAEXXZ"

[header]
name = "?_ReleaseAlias@_TaskCollection@details@Concurrency@@AAEXXZ"
addr = 0x3cbb34

[header.args]
