last_change = 2026-06-27T20:52:06.456017Z
addr = 0x3d0fa7
size = 0x36
name = "??$sign@N@details@Concurrency@@YANN@Z"

[header]
name = "??$sign@N@details@Concurrency@@YANN@Z"
addr = 0x3d0fa7

[header.args]
