last_change = 2026-06-27T20:52:06.456279Z
addr = 0x3d8726
size = 0x2b
name = "?SpinUntilBlocked@ThreadProxy@details@Concurrency@@QAEXXZ"

[header]
name = "?SpinUntilBlocked@ThreadProxy@details@Concurrency@@QAEXXZ"
addr = 0x3d8726

[header.args]
