last_change = 2026-06-27T20:52:06.456185Z
addr = 0x3d66b8
size = 0x97
name = "?GetLocalRunnable@WorkSearchContext@details@Concurrency@@AAE_NPAVWorkItem@23@PAVVirtualProcessor@23@_N@Z"

[header]
name = "?GetLocalRunnable@WorkSearchContext@details@Concurrency@@AAE_NPAVWorkItem@23@PAVVirtualProcessor@23@_N@Z"
addr = 0x3d66b8

[header.args]
