last_change = 2026-06-27T20:52:06.456234Z
addr = 0x3d7a07
size = 0x17
name = "?StealLocalRunnableContext@VirtualProcessor@details@Concurrency@@AAEPAVInternalContextBase@23@XZ"

[header]
name = "?StealLocalRunnableContext@VirtualProcessor@details@Concurrency@@AAEPAVInternalContextBase@23@XZ"
addr = 0x3d7a07

[header.args]
