last_change = 2026-06-27T20:52:06.456435Z
addr = 0x42bff0
size = 0x8
name = "__unwindfunclet$?VirtualProcessorActiveNotification@UMSThreadScheduler@details@Concurrency@@MAEX_NJ@Z$0"

[header]
name = "__unwindfunclet$?VirtualProcessorActiveNotification@UMSThreadScheduler@details@Concurrency@@MAEX_NJ@Z$0"
addr = 0x42bff0

[header.args]
