last_change = 2026-06-27T20:52:06.456476Z
addr = 0x436bdb
size = 0xb
name = "__unwindfunclet$??1SchedulerBase@details@Concurrency@@UAE@XZ$2"

[header]
name = "__unwindfunclet$??1SchedulerBase@details@Concurrency@@UAE@XZ$2"
addr = 0x436bdb

[header.args]
