last_change = 2026-06-27T20:52:06.456533Z
addr = 0x437707
size = 0x8
name = "__unwindfunclet$?_CopyException@__ExceptionPtr@@SA?AV?$shared_ptr@V__ExceptionPtr@@@std@@PBXPBU_s_ThrowInfo@@_N@Z$8"

[header]
name = "__unwindfunclet$?_CopyException@__ExceptionPtr@@SA?AV?$shared_ptr@V__ExceptionPtr@@@std@@PBXPBU_s_ThrowInfo@@_N@Z$8"
addr = 0x437707

[header.args]
