last_change = 2026-06-27T20:52:06.456490Z
addr = 0x436c83
size = 0xb
name = "__unwindfunclet$??1SchedulerBase@details@Concurrency@@UAE@XZ$3"

[header]
name = "__unwindfunclet$??1SchedulerBase@details@Concurrency@@UAE@XZ$3"
addr = 0x436c83

[header.args]
