last_change = 2026-06-27T20:49:16.840188Z
name = "__NCRYPT_KEY_ACCESS_POLICY_BLOB"
size = 0x10

[members.0x0]
name = "dwVersion"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwPolicyFlags"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "cbUserSid"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "cbApplicationSid"
offset = 0xc
type = "DWORD"
size = 0x4
