last_change = 2026-06-27T20:49:16.630915Z
name = "_ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION"
size = 0xc

[members.0x0]
name = "ElementCount"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x8]
name = "Elements"
offset = 0x8
type = "COMPATIBILITY_CONTEXT_ELEMENT*"
size = 0x4
