last_change = 2026-06-27T20:49:16.636186Z
name = "_BCRYPT_RSAKEY_BLOB"
size = 0x18

[members.0x0]
name = "Magic"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "BitLength"
offset = 0x4
type = "ULONG"
size = 0x4

[members.0x8]
name = "cbPublicExp"
offset = 0x8
type = "ULONG"
size = 0x4

[members.0xc]
name = "cbModulus"
offset = 0xc
type = "ULONG"
size = 0x4

[members.0x10]
name = "cbPrime1"
offset = 0x10
type = "ULONG"
size = 0x4

[members.0x14]
name = "cbPrime2"
offset = 0x14
type = "ULONG"
size = 0x4
