last_change = 2026-06-27T20:49:16.638774Z
name = "_CACHE_RELATIONSHIP"
size = 0x2c

[members.0x0]
name = "Level"
offset = 0x0
type = "BYTE"
size = 0x1

[members.0x1]
name = "Associativity"
offset = 0x1
type = "BYTE"
size = 0x1

[members.0x2]
name = "LineSize"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "CacheSize"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Type"
offset = 0x8
type = "PROCESSOR_CACHE_TYPE"
size = 0x4

[members.0xc]
name = "Reserved"
offset = 0xc
type = "BYTE[0x12]"
size = 0x12

[members.0x1e]
name = "GroupCount"
offset = 0x1e
type = "WORD"
size = 0x2

[members.0x20]
name = ""
offset = 0x20
type = "union"
size = 0xc
