last_change = 2026-06-27T20:49:16.641404Z
name = "_CERT_ECC_SIGNATURE"
size = 0x10

[members.0x0]
name = "r"
offset = 0x0
type = "CRYPT_UINT_BLOB"
size = 0x8

[members.0x8]
name = "s"
offset = 0x8
type = "CRYPT_UINT_BLOB"
size = 0x8
