last_change = 2026-06-27T20:49:16.643779Z
name = "_CERT_OR_CRL_BUNDLE"
size = 0x8

[members.0x0]
name = "cItem"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "rgItem"
offset = 0x4
type = "PCERT_OR_CRL_BLOB"
size = 0x4
