last_change = 2026-06-27T20:49:16.646730Z
name = "_CERT_REVOCATION_STATUS"
size = 0x18

[members.0x0]
name = "cbSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwIndex"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwError"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwReason"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "fHasFreshnessTime"
offset = 0x10
type = "BOOL"
size = 0x4

[members.0x14]
name = "dwFreshnessTime"
offset = 0x14
type = "DWORD"
size = 0x4
