last_change = 2026-06-27T20:49:16.641815Z
name = "_CERT_HASHED_URL"
size = 0x18

[members.0x0]
name = "HashAlgorithm"
offset = 0x0
type = "CRYPT_ALGORITHM_IDENTIFIER"
size = 0xc

[members.0xc]
name = "Hash"
offset = 0xc
type = "CRYPT_HASH_BLOB"
size = 0x8

[members.0x14]
name = "pwszUrl"
offset = 0x14
type = "LPWSTR"
size = 0x4
