last_change = 2026-06-27T20:49:16.652391Z
name = "_CMSG_CMS_RECIPIENT_INFO"
size = 0x8

[members.0x0]
name = "dwRecipientChoice"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = ""
offset = 0x4
type = "union"
size = 0x4
