last_change = 2026-06-27T20:49:16.653863Z
name = "_CMSG_CTRL_VERIFY_SIGNATURE_EX_PARA"
size = 0x14

[members.0x0]
name = "cbSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "hCryptProv"
offset = 0x4
type = "HCRYPTPROV_LEGACY"
size = 0x4

[members.0x8]
name = "dwSignerIndex"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwSignerType"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "pvSigner"
offset = 0x10
type = "void*"
size = 0x4
