last_change = 2026-06-27T20:49:16.654180Z
name = "_CMSG_HASHED_ENCODE_INFO"
size = 0x18

[members.0x0]
name = "cbSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "hCryptProv"
offset = 0x4
type = "HCRYPTPROV_LEGACY"
size = 0x4

[members.0x8]
name = "HashAlgorithm"
offset = 0x8
type = "CRYPT_ALGORITHM_IDENTIFIER"
size = 0xc

[members.0x14]
name = "pvHashAuxInfo"
offset = 0x14
type = "void*"
size = 0x4
