last_change = 2026-06-27T20:49:16.667982Z
name = "_CRYPT_PASSWORD_CREDENTIALSW"
size = 0xc

[members.0x0]
name = "cbSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "pszUsername"
offset = 0x4
type = "LPWSTR"
size = 0x4

[members.0x8]
name = "pszPassword"
offset = 0x8
type = "LPWSTR"
size = 0x4
