last_change = 2026-06-27T20:49:16.664523Z
name = "_CRYPT_CONTEXT_FUNCTIONS"
size = 0x8

[members.0x0]
name = "cFunctions"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "rgpszFunctions"
offset = 0x4
type = "PWSTR*"
size = 0x4
