last_change = 2026-06-27T20:49:16.670239Z
name = "_CRYPT_TIMESTAMP_CONTEXT"
size = 0xc

[members.0x0]
name = "cbEncoded"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "pbEncoded"
offset = 0x4
type = "BYTE*"
size = 0x4

[members.0x8]
name = "pTimeStamp"
offset = 0x8
type = "PCRYPT_TIMESTAMP_INFO"
size = 0x4
