last_change = 2026-06-27T20:49:16.663830Z
name = "_CRYPT_ATTRIBUTE_TYPE_VALUE"
size = 0xc

[members.0x0]
name = "pszObjId"
offset = 0x0
type = "LPSTR"
size = 0x4

[members.0x4]
name = "Value"
offset = 0x4
type = "CRYPT_OBJID_BLOB"
size = 0x8
