last_change = 2026-06-27T20:49:16.677669Z
name = "_DEVICE_DSM_LOST_QUERY_PARAMETERS"
size = 0x10

[members.0x0]
name = "Version"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x8]
name = "Granularity"
offset = 0x8
type = "DWORDLONG"
size = 0x8
