last_change = 2026-06-27T20:49:16.681423Z
name = "_DISK_EX_INT13_INFO"
size = 0x20

[members.0x0]
name = "ExBufferSize"
offset = 0x0
type = "WORD"
size = 0x2

[members.0x2]
name = "ExFlags"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "ExCylinders"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "ExHeads"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "ExSectorsPerTrack"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "ExSectorsPerDrive"
offset = 0x10
type = "DWORD64"
size = 0x8

[members.0x18]
name = "ExSectorSize"
offset = 0x18
type = "WORD"
size = 0x2

[members.0x1a]
name = "ExReserved"
offset = 0x1a
type = "WORD"
size = 0x2
