last_change = 2026-06-27T20:49:16.681894Z
name = "_DISK_HISTOGRAM"
size = 0x48

[members.0x0]
name = "DiskSize"
offset = 0x0
type = "LARGE_INTEGER"
size = 0x8

[members.0x8]
name = "Start"
offset = 0x8
type = "LARGE_INTEGER"
size = 0x8

[members.0x10]
name = "End"
offset = 0x10
type = "LARGE_INTEGER"
size = 0x8

[members.0x18]
name = "Average"
offset = 0x18
type = "LARGE_INTEGER"
size = 0x8

[members.0x20]
name = "AverageRead"
offset = 0x20
type = "LARGE_INTEGER"
size = 0x8

[members.0x28]
name = "AverageWrite"
offset = 0x28
type = "LARGE_INTEGER"
size = 0x8

[members.0x30]
name = "Granularity"
offset = 0x30
type = "DWORD"
size = 0x4

[members.0x34]
name = "Size"
offset = 0x34
type = "DWORD"
size = 0x4

[members.0x38]
name = "ReadCount"
offset = 0x38
type = "DWORD"
size = 0x4

[members.0x3c]
name = "WriteCount"
offset = 0x3c
type = "DWORD"
size = 0x4

[members.0x40]
name = "Histogram"
offset = 0x40
type = "PHISTOGRAM_BUCKET"
size = 0x4
