last_change = 2026-06-27T20:49:16.683246Z
name = "_DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO"
size = 0x20

[members.0x0]
name = "header"
offset = 0x0
type = "struct DISPLAYCONFIG_DEVICE_INFO_HEADER"
size = 0x14

[members.0x14]
name = ""
offset = 0x14
type = "union"
size = 0x4

[members.0x18]
name = "colorEncoding"
offset = 0x18
type = "DISPLAYCONFIG_COLOR_ENCODING"
size = 0x4

[members.0x1c]
name = "bitsPerColorChannel"
offset = 0x1c
type = "UINT32"
size = 0x4
