last_change = 2026-06-27T20:49:16.691553Z
name = "_ENCRYPTION_BUFFER"
size = 0x8

[members.0x0]
name = "EncryptionOperation"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Private"
offset = 0x4
type = "BYTE[0x1]"
size = 0x1
