last_change = 2026-06-27T20:49:16.690759Z
name = "_ENCLAVE_CREATE_INFO_VBS"
size = 0x24

[members.0x0]
name = "Flags"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "OwnerID"
offset = 0x4
type = "BYTE[0x20]"
size = 0x20
