last_change = 2026-06-27T20:49:16.693563Z
name = "_EV_EXTRA_CERT_CHAIN_POLICY_STATUS"
size = 0xc

[members.0x0]
name = "cbSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwQualifiers"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwIssuanceUsageIndex"
offset = 0x8
type = "DWORD"
size = 0x4
