last_change = 2026-06-27T20:49:16.700634Z
name = "_FILE_REFERENCE_RANGE"
size = 0x10

[members.0x0]
name = "StartingFileReferenceNumber"
offset = 0x0
type = "DWORDLONG"
size = 0x8

[members.0x8]
name = "EndingFileReferenceNumber"
offset = 0x8
type = "DWORDLONG"
size = 0x8
