last_change = 2026-06-27T20:49:16.703204Z
name = "_FLAGGED_WORD_BLOB"
size = 0xc

[members.0x0]
name = "fFlags"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "clSize"
offset = 0x4
type = "ULONG"
size = 0x4

[members.0x8]
name = "asData"
offset = 0x8
type = "ushort[0x1]"
size = 0x2
