last_change = 2026-06-27T20:49:16.703639Z
name = "_FLOATING_SAVE_AREA"
size = 0x70

[members.0x0]
name = "ControlWord"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "StatusWord"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "TagWord"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "ErrorOffset"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "ErrorSelector"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "DataOffset"
offset = 0x14
type = "DWORD"
size = 0x4

[members.0x18]
name = "DataSelector"
offset = 0x18
type = "DWORD"
size = 0x4

[members.0x1c]
name = "RegisterArea"
offset = 0x1c
type = "BYTE[0x50]"
size = 0x50

[members.0x6c]
name = "Spare0"
offset = 0x6c
type = "DWORD"
size = 0x4
