last_change = 2026-06-27T20:49:16.706762Z
name = "_GDI_NONREMOTE"
size = 0x8

[members.0x0]
name = "fContext"
offset = 0x0
type = "LONG"
size = 0x4

[members.0x4]
name = "u"
offset = 0x4
type = "union"
size = 0x4
