last_change = 2026-06-27T20:49:16.709629Z
name = "_HTTPSPolicyCallbackData"
size = 0x10

[members.0x0]
name = ""
offset = 0x0
type = "union"
size = 0x4

[members.0x4]
name = "dwAuthType"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "fdwChecks"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "pwszServerName"
offset = 0xc
type = "WCHAR*"
size = 0x4
