last_change = 2026-06-27T20:49:16.722616Z
name = "_ImageArchitectureHeader"
size = 0x8

[members.0x0]
name = "__bitfield0"
offset = 0x0
type = "union"
size = 0x4

[members.0x4]
name = "FirstEntryRVA"
offset = 0x4
type = "DWORD"
size = 0x4
