last_change = 2026-06-27T20:49:16.722764Z
name = "_JIT_DEBUG_INFO"
size = 0x28

[members.0x0]
name = "dwSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwProcessorArchitecture"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwThreadID"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwReserved0"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "lpExceptionAddress"
offset = 0x10
type = "ULONG64"
size = 0x8

[members.0x18]
name = "lpExceptionRecord"
offset = 0x18
type = "ULONG64"
size = 0x8

[members.0x20]
name = "lpContextRecord"
offset = 0x20
type = "ULONG64"
size = 0x8
