last_change = 2026-06-27T20:49:16.731402Z
name = "_LUID_AND_ATTRIBUTES"
size = 0xc

[members.0x0]
name = "Luid"
offset = 0x0
type = "LUID"
size = 0x8

[members.0x8]
name = "Attributes"
offset = 0x8
type = "DWORD"
size = 0x4
