last_change = 2026-06-27T20:49:16.731940Z
name = "_MEMORYSTATUS"
size = 0x20

[members.0x0]
name = "dwLength"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwMemoryLoad"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwTotalPhys"
offset = 0x8
type = "SIZE_T"
size = 0x4

[members.0xc]
name = "dwAvailPhys"
offset = 0xc
type = "SIZE_T"
size = 0x4

[members.0x10]
name = "dwTotalPageFile"
offset = 0x10
type = "SIZE_T"
size = 0x4

[members.0x14]
name = "dwAvailPageFile"
offset = 0x14
type = "SIZE_T"
size = 0x4

[members.0x18]
name = "dwTotalVirtual"
offset = 0x18
type = "SIZE_T"
size = 0x4

[members.0x1c]
name = "dwAvailVirtual"
offset = 0x1c
type = "SIZE_T"
size = 0x4
