last_change = 2026-06-27T20:49:16.737599Z
name = "_MODEMSETTINGS"
size = 0x30

[members.0x0]
name = "dwActualSize"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwRequiredSize"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwDevSpecificOffset"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwDevSpecificSize"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "dwCallSetupFailTimer"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "dwInactivityTimeout"
offset = 0x14
type = "DWORD"
size = 0x4

[members.0x18]
name = "dwSpeakerVolume"
offset = 0x18
type = "DWORD"
size = 0x4

[members.0x1c]
name = "dwSpeakerMode"
offset = 0x1c
type = "DWORD"
size = 0x4

[members.0x20]
name = "dwPreferredModemOptions"
offset = 0x20
type = "DWORD"
size = 0x4

[members.0x24]
name = "dwNegotiatedModemOptions"
offset = 0x24
type = "DWORD"
size = 0x4

[members.0x28]
name = "dwNegotiatedDCERate"
offset = 0x28
type = "DWORD"
size = 0x4

[members.0x2c]
name = "abVariablePortion"
offset = 0x2c
type = "BYTE[0x1]"
size = 0x1
