last_change = 2026-06-27T20:49:16.745167Z
name = "_NUMPARSE"
size = 0x18

[members.0x0]
name = "cDig"
offset = 0x0
type = "INT"
size = 0x4

[members.0x4]
name = "dwInFlags"
offset = 0x4
type = "ULONG"
size = 0x4

[members.0x8]
name = "dwOutFlags"
offset = 0x8
type = "ULONG"
size = 0x4

[members.0xc]
name = "cchUsed"
offset = 0xc
type = "INT"
size = 0x4

[members.0x10]
name = "nBaseShift"
offset = 0x10
type = "INT"
size = 0x4

[members.0x14]
name = "nPwr10"
offset = 0x14
type = "INT"
size = 0x4
