last_change = 2026-06-27T20:49:16.753036Z
name = "_PARTITION_INFORMATION_MBR"
size = 0x18

[members.0x0]
name = "PartitionType"
offset = 0x0
type = "BYTE"
size = 0x1

[members.0x1]
name = "BootIndicator"
offset = 0x1
type = "BOOLEAN"
size = 0x1

[members.0x2]
name = "RecognizedPartition"
offset = 0x2
type = "BOOLEAN"
size = 0x1

[members.0x4]
name = "HiddenSectors"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "PartitionId"
offset = 0x8
type = "GUID"
size = 0x10
