last_change = 2026-06-27T20:49:16.759350Z
name = "_PPM_PERFSTATE_EVENT"
size = 0x14

[members.0x0]
name = "State"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Status"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Latency"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "Speed"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "Processor"
offset = 0x10
type = "DWORD"
size = 0x4
