last_change = 2026-06-27T20:49:16.764063Z
name = "_PRINTER_NOTIFY_INFO_DATA"
size = 0x14

[members.0x0]
name = "Type"
offset = 0x0
type = "WORD"
size = 0x2

[members.0x2]
name = "Field"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "Reserved"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Id"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "NotifyData"
offset = 0xc
type = "union"
size = 0x8
