last_change = 2026-06-27T20:49:16.764944Z
name = "_PRIVILEGE_SET"
size = 0x14

[members.0x0]
name = "PrivilegeCount"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Control"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Privilege"
offset = 0x8
type = "LUID_AND_ATTRIBUTES[0x1]"
size = 0xc
