last_change = 2026-06-27T20:49:16.761852Z
name = "_PRINTER_INFO_1A"
size = 0x10

[members.0x0]
name = "Flags"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "pDescription"
offset = 0x4
type = "LPSTR"
size = 0x4

[members.0x8]
name = "pName"
offset = 0x8
type = "LPSTR"
size = 0x4

[members.0xc]
name = "pComment"
offset = 0xc
type = "LPSTR"
size = 0x4
