last_change = 2026-06-27T20:49:16.765809Z
name = "_PROCESSOR_PERFSTATE_POLICY"
size = 0x1c

[members.0x0]
name = "Revision"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "MaxThrottle"
offset = 0x4
type = "BYTE"
size = 0x1

[members.0x5]
name = "MinThrottle"
offset = 0x5
type = "BYTE"
size = 0x1

[members.0x6]
name = "BusyAdjThreshold"
offset = 0x6
type = "BYTE"
size = 0x1

[members.0x7]
name = ""
offset = 0x7
type = "union"
size = 0x1

[members.0x8]
name = "TimeCheck"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "IncreaseTime"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "DecreaseTime"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "IncreasePercent"
offset = 0x14
type = "DWORD"
size = 0x4

[members.0x18]
name = "DecreasePercent"
offset = 0x18
type = "DWORD"
size = 0x4
