last_change = 2026-06-27T20:49:16.773240Z
name = "_PUBKEYVER3"
size = 0x28

[members.0x0]
name = "magic"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "bitlenP"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "bitlenQ"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "bitlenJ"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "DSSSeed"
offset = 0x10
type = "DSSSEED"
size = 0x18
