last_change = 2026-06-27T20:49:16.777968Z
name = "_REPAIR_COPIES_INPUT"
size = 0x20

[members.0x0]
name = "Size"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Flags"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "FileOffset"
offset = 0x8
type = "LARGE_INTEGER"
size = 0x8

[members.0x10]
name = "Length"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "SourceCopy"
offset = 0x14
type = "DWORD"
size = 0x4

[members.0x18]
name = "NumberOfRepairCopies"
offset = 0x18
type = "DWORD"
size = 0x4

[members.0x1c]
name = "RepairCopies"
offset = 0x1c
type = "DWORD[0x1]"
size = 0x4
