last_change = 2026-06-27T20:49:16.778049Z
name = "_REPAIR_COPIES_OUTPUT"
size = 0x10

[members.0x0]
name = "Size"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Status"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "ResumeFileOffset"
offset = 0x8
type = "LARGE_INTEGER"
size = 0x8
