last_change = 2026-06-27T20:49:16.778266Z
name = "_REQUEST_OPLOCK_INPUT_BUFFER"
size = 0xc

[members.0x0]
name = "StructureVersion"
offset = 0x0
type = "WORD"
size = 0x2

[members.0x2]
name = "StructureLength"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "RequestedOplockLevel"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Flags"
offset = 0x8
type = "DWORD"
size = 0x4
