last_change = 2026-06-27T20:49:16.784748Z
name = "_RPC_SEC_CONTEXT_KEY_INFO"
size = 0xc

[members.0x0]
name = "EncryptAlgorithm"
offset = 0x0
type = "uint"
size = 0x4

[members.0x4]
name = "KeySize"
offset = 0x4
type = "uint"
size = 0x4

[members.0x8]
name = "SignatureAlgorithm"
offset = 0x8
type = "uint"
size = 0x4
