last_change = 2026-06-27T20:49:16.782312Z
name = "_RPC_IF_ID_VECTOR"
size = 0x8

[members.0x0]
name = "Count"
offset = 0x0
type = "uint"
size = 0x4

[members.0x4]
name = "IfId"
offset = 0x4
type = "RPC_IF_ID*[0x1]"
size = 0x4
