last_change = 2026-06-27T20:49:16.788114Z
name = "_SCHANNEL_ALG"
size = 0x14

[members.0x0]
name = "dwUse"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Algid"
offset = 0x4
type = "ALG_ID"
size = 0x4

[members.0x8]
name = "cBits"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwFlags"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "dwReserved"
offset = 0x10
type = "DWORD"
size = 0x4
