last_change = 2026-06-27T20:49:16.794029Z
name = "_SD_ENUM_SDS_INPUT"
size = 0x10

[members.0x0]
name = "StartingOffset"
offset = 0x0
type = "DWORDLONG"
size = 0x8

[members.0x8]
name = "MaxSDEntriesToReturn"
offset = 0x8
type = "DWORDLONG"
size = 0x8
