last_change = 2026-06-27T20:49:16.799680Z
name = "_SE_ACCESS_REPLY"
size = 0x18

[members.0x0]
name = "Size"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "ResultListCount"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "GrantedAccess"
offset = 0x8
type = "PACCESS_MASK"
size = 0x4

[members.0xc]
name = "AccessStatus"
offset = 0xc
type = "PDWORD"
size = 0x4

[members.0x10]
name = "AccessReason"
offset = 0x10
type = "PACCESS_REASONS"
size = 0x4

[members.0x14]
name = "Privileges"
offset = 0x14
type = "PPRIVILEGE_SET*"
size = 0x4
