last_change = 2026-06-27T20:49:16.800029Z
name = "_SE_SECURITY_DESCRIPTOR"
size = 0xc

[members.0x0]
name = "Size"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Flags"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "SecurityDescriptor"
offset = 0x8
type = "PSECURITY_DESCRIPTOR"
size = 0x4
