last_change = 2026-06-27T20:49:16.795416Z
name = "_SEC_WINNT_AUTH_IDENTITY_W"
size = 0x1c

[members.0x0]
name = "User"
offset = 0x0
type = "ushort*"
size = 0x4

[members.0x4]
name = "UserLength"
offset = 0x4
type = "uint"
size = 0x4

[members.0x8]
name = "Domain"
offset = 0x8
type = "ushort*"
size = 0x4

[members.0xc]
name = "DomainLength"
offset = 0xc
type = "uint"
size = 0x4

[members.0x10]
name = "Password"
offset = 0x10
type = "ushort*"
size = 0x4

[members.0x14]
name = "PasswordLength"
offset = 0x14
type = "uint"
size = 0x4

[members.0x18]
name = "Flags"
offset = 0x18
type = "uint"
size = 0x4
