last_change = 2026-06-27T20:49:16.794594Z
name = "_SECURITY_ATTRIBUTES"
size = 0xc

[members.0x0]
name = "nLength"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "lpSecurityDescriptor"
offset = 0x4
type = "LPVOID"
size = 0x4

[members.0x8]
name = "bInheritHandle"
offset = 0x8
type = "BOOL"
size = 0x4
