last_change = 2026-06-27T20:49:16.797763Z
name = "_SERVICE_STATUS"
size = 0x1c

[members.0x0]
name = "dwServiceType"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwCurrentState"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwControlsAccepted"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwWin32ExitCode"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "dwServiceSpecificExitCode"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "dwCheckPoint"
offset = 0x14
type = "DWORD"
size = 0x4

[members.0x18]
name = "dwWaitHint"
offset = 0x18
type = "DWORD"
size = 0x4
