last_change = 2026-06-27T20:49:16.798805Z
name = "_SERVICE_TRIGGER_SPECIFIC_DATA_ITEM"
size = 0xc

[members.0x0]
name = "dwDataType"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "cbData"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "pData"
offset = 0x8
type = "PBYTE"
size = 0x4
