last_change = 2026-06-27T20:49:16.807265Z
name = "_STORAGE_DEVICE_MANAGEMENT_STATUS"
size = 0x64

[members.0x0]
name = "Version"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Size"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Health"
offset = 0x8
type = "STORAGE_DISK_HEALTH_STATUS"
size = 0x4

[members.0xc]
name = "NumberOfOperationalStatus"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "NumberOfAdditionalReasons"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "OperationalStatus"
offset = 0x14
type = "STORAGE_DISK_OPERATIONAL_STATUS[0x10]"
size = 0x40

[members.0x54]
name = "AdditionalReasons"
offset = 0x54
type = "STORAGE_OPERATIONAL_REASON[0x1]"
size = 0x10
