last_change = 2026-06-27T20:49:16.808485Z
name = "_STORAGE_DIAGNOSTIC_REQUEST"
size = 0x14

[members.0x0]
name = "Version"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Size"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "Flags"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "TargetType"
offset = 0xc
type = "STORAGE_DIAGNOSTIC_TARGET_TYPE"
size = 0x4

[members.0x10]
name = "Level"
offset = 0x10
type = "STORAGE_DIAGNOSTIC_LEVEL"
size = 0x4
