last_change = 2026-06-27T20:49:16.809257Z
name = "_STORAGE_HW_ENDURANCE_DATA_DESCRIPTOR"
size = 0x38

[members.0x0]
name = "Version"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Size"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "EnduranceInfo"
offset = 0x8
type = "STORAGE_HW_ENDURANCE_INFO"
size = 0x30
