last_change = 2026-06-27T20:49:16.845001Z
name = "_tagSOFTDISTINFO"
size = 0x34

[members.0x0]
name = "cbSize"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "dwFlags"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwAdState"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "szTitle"
offset = 0xc
type = "LPWSTR"
size = 0x4

[members.0x10]
name = "szAbstract"
offset = 0x10
type = "LPWSTR"
size = 0x4

[members.0x14]
name = "szHREF"
offset = 0x14
type = "LPWSTR"
size = 0x4

[members.0x18]
name = "dwInstalledVersionMS"
offset = 0x18
type = "DWORD"
size = 0x4

[members.0x1c]
name = "dwInstalledVersionLS"
offset = 0x1c
type = "DWORD"
size = 0x4

[members.0x20]
name = "dwUpdateVersionMS"
offset = 0x20
type = "DWORD"
size = 0x4

[members.0x24]
name = "dwUpdateVersionLS"
offset = 0x24
type = "DWORD"
size = 0x4

[members.0x28]
name = "dwAdvertisedVersionMS"
offset = 0x28
type = "DWORD"
size = 0x4

[members.0x2c]
name = "dwAdvertisedVersionLS"
offset = 0x2c
type = "DWORD"
size = 0x4

[members.0x30]
name = "dwReserved"
offset = 0x30
type = "DWORD"
size = 0x4
