last_change = 2026-06-27T20:49:16.832311Z
name = "_USN_JOURNAL_DATA_V2"
size = 0x50

[members.0x0]
name = "UsnJournalID"
offset = 0x0
type = "DWORDLONG"
size = 0x8

[members.0x8]
name = "FirstUsn"
offset = 0x8
type = "USN"
size = 0x8

[members.0x10]
name = "NextUsn"
offset = 0x10
type = "USN"
size = 0x8

[members.0x18]
name = "LowestValidUsn"
offset = 0x18
type = "USN"
size = 0x8

[members.0x20]
name = "MaxUsn"
offset = 0x20
type = "USN"
size = 0x8

[members.0x28]
name = "MaximumSize"
offset = 0x28
type = "DWORDLONG"
size = 0x8

[members.0x30]
name = "AllocationDelta"
offset = 0x30
type = "DWORDLONG"
size = 0x8

[members.0x38]
name = "MinSupportedMajorVersion"
offset = 0x38
type = "WORD"
size = 0x2

[members.0x3a]
name = "MaxSupportedMajorVersion"
offset = 0x3a
type = "WORD"
size = 0x2

[members.0x3c]
name = "Flags"
offset = 0x3c
type = "DWORD"
size = 0x4

[members.0x40]
name = "RangeTrackChunkSize"
offset = 0x40
type = "DWORDLONG"
size = 0x8

[members.0x48]
name = "RangeTrackFileSizeThreshold"
offset = 0x48
type = "LONGLONG"
size = 0x8
