last_change = 2026-06-27T20:49:16.837770Z
name = "_WOW64_DESCRIPTOR_TABLE_ENTRY"
size = 0xc

[members.0x0]
name = "Selector"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "Descriptor"
offset = 0x4
type = "WOW64_LDT_ENTRY"
size = 0x8
