last_change = 2026-06-27T20:49:16.838103Z
name = "_WRITE_USN_REASON_INPUT"
size = 0x8

[members.0x0]
name = "Flags"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "UsnReasonToWrite"
offset = 0x4
type = "DWORD"
size = 0x4
