last_change = 2026-06-27T20:49:16.580042Z
name = "AA_CGlobalTextureData"
size = 0x20

[members.0x0]
name = "m_TextureList"
offset = 0x0
type = "struct IDirect3DTexture9*"
size = 0x4

[members.0x4]
name = "m_TextureList2"
offset = 0x4
type = "struct IDirect3DTexture9*"
size = 0x4

[members.0x8]
name = "m_TotalCount"
offset = 0x8
type = "uint"
size = 0x4

[members.0xc]
name = "m_Count"
offset = 0xc
type = "uint"
size = 0x4

[members.0x10]
name = "m_Width"
offset = 0x10
type = "uint"
size = 0x4

[members.0x14]
name = "m_Height"
offset = 0x14
type = "uint"
size = 0x4

[members.0x18]
name = "m_Format"
offset = 0x18
type = "uint"
size = 0x4

[members.0x1c]
name = "m_MipLevels"
offset = 0x1c
type = "uint"
size = 0x4
