last_change = 2026-06-27T20:49:16.583726Z
name = "AA_LinearColor"
size = 0x10

[members.0x0]
name = "A"
offset = 0x0
type = "float"
size = 0x4

[members.0x4]
name = "R"
offset = 0x4
type = "float"
size = 0x4

[members.0x8]
name = "G"
offset = 0x8
type = "float"
size = 0x4

[members.0xc]
name = "B"
offset = 0xc
type = "float"
size = 0x4
