last_change = 2026-06-27T20:49:16.601625Z
name = "DISPLAYCONFIG_2DREGION"
size = 0x8

[members.0x0]
name = "cx"
offset = 0x0
type = "UINT32"
size = 0x4

[members.0x4]
name = "cy"
offset = 0x4
type = "UINT32"
size = 0x4
