last_change = 2026-06-27T20:49:16.614263Z
name = "IDirect3DStateBlock9VTable"
size = 0x18

[members.0xc]
name = "GetDevice"
offset = 0xc
type = "HRESULT (*)(struct IDirect3DStateBlock9* this, struct IDirect3DDevice9* ppDevice)"
size = 0x4

[members.0x10]
name = "Capture"
offset = 0x10
type = "HRESULT (*)(struct IDirect3DStateBlock9* this)"
size = 0x4

[members.0x14]
name = "Apply"
offset = 0x14
type = "HRESULT (*)(struct IDirect3DStateBlock9* this)"
size = 0x4
