last_change = 2026-06-27T20:49:16.626865Z
name = "SCENE_CBattle"
size = 0x74

[members.0x0]
name = "vftable"
offset = 0x0
type = "struct SCENE_CBattleVTable*"
size = 0x4

[members.0x18]
name = "m_Tasks"
offset = 0x18
type = "struct AA_TaskList"
size = 0x10

[members.0x28]
name = "unk28"
offset = 0x28
type = "uint"
size = 0x4

[members.0x2c]
name = "m_GameSceneStatus"
offset = 0x2c
type = "enum SCENE_STATUS"
size = 0x4

[members.0x44]
name = "m_bLogDisabled"
offset = 0x44
type = "bool"
size = 0x1

[members.0x60]
name = "m_TrainingMenuRequest"
offset = 0x60
type = "int"
size = 0x4

[members.0x64]
name = "field_64"
offset = 0x64
type = "int"
size = 0x4

[members.0x68]
name = "m_GoToVsInfo"
offset = 0x68
type = "int"
size = 0x4

[members.0x6c]
name = "m_PendingTaskID"
offset = 0x6c
type = "int"
size = 0x4

[members.0x70]
name = "m_BattleStatus"
offset = 0x70
type = "int"
size = 0x4
