last_change = 2026-06-27T20:49:16.858735Z
name = "tagCIEXYZ"
size = 0xc

[members.0x0]
name = "ciexyzX"
offset = 0x0
type = "FXPT2DOT30"
size = 0x4

[members.0x4]
name = "ciexyzY"
offset = 0x4
type = "FXPT2DOT30"
size = 0x4

[members.0x8]
name = "ciexyzZ"
offset = 0x8
type = "FXPT2DOT30"
size = 0x4
