last_change = 2026-06-27T20:49:16.861157Z
name = "tagCSPLATFORM"
size = 0x10

[members.0x0]
name = "dwPlatformId"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwVersionHi"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "dwVersionLo"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwProcessorArch"
offset = 0xc
type = "DWORD"
size = 0x4
