last_change = 2026-06-27T20:49:16.855965Z
name = "tagCAC"
size = 0x8

[members.0x0]
name = "cElems"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "pElems"
offset = 0x4
type = "CHAR*"
size = 0x4
