last_change = 2026-06-27T20:49:16.871352Z
name = "tagEMRSETPALETTEENTRIES"
size = 0x18

[members.0x0]
name = "emr"
offset = 0x0
type = "EMR"
size = 0x8

[members.0x8]
name = "ihPal"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "iStart"
offset = 0xc
type = "DWORD"
size = 0x4

[members.0x10]
name = "cEntries"
offset = 0x10
type = "DWORD"
size = 0x4

[members.0x14]
name = "aPalEntries"
offset = 0x14
type = "PALETTEENTRY[0x1]"
size = 0x4
