last_change = 2026-06-27T20:49:16.878253Z
name = "tagHIGHCONTRASTA"
size = 0xc

[members.0x0]
name = "cbSize"
offset = 0x0
type = "UINT"
size = 0x4

[members.0x4]
name = "dwFlags"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "lpszDefaultScheme"
offset = 0x8
type = "LPSTR"
size = 0x4
