last_change = 2026-06-27T20:49:16.882552Z
name = "tagKERNINGPAIR"
size = 0x8

[members.0x0]
name = "wFirst"
offset = 0x0
type = "WORD"
size = 0x2

[members.0x2]
name = "wSecond"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "iKernAmount"
offset = 0x4
type = "int"
size = 0x4
