last_change = 2026-06-27T20:49:16.887208Z
name = "tagMCI_OVLY_SAVE_PARMSA"
size = 0x18

[members.0x0]
name = "dwCallback"
offset = 0x0
type = "DWORD_PTR"
size = 0x4

[members.0x4]
name = "lpfilename"
offset = 0x4
type = "LPCSTR"
size = 0x4

[members.0x8]
name = "rc"
offset = 0x8
type = "RECT"
size = 0x10
