last_change = 2026-06-27T20:49:16.892653Z
name = "tagMIDIOUTCAPSA"
size = 0x34

[members.0x0]
name = "wMid"
offset = 0x0
type = "WORD"
size = 0x2

[members.0x2]
name = "wPid"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "vDriverVersion"
offset = 0x4
type = "MMVERSION"
size = 0x4

[members.0x8]
name = "szPname"
offset = 0x8
type = "CHAR[0x20]"
size = 0x20

[members.0x28]
name = "wTechnology"
offset = 0x28
type = "WORD"
size = 0x2

[members.0x2a]
name = "wVoices"
offset = 0x2a
type = "WORD"
size = 0x2

[members.0x2c]
name = "wNotes"
offset = 0x2c
type = "WORD"
size = 0x2

[members.0x2e]
name = "wChannelMask"
offset = 0x2e
type = "WORD"
size = 0x2

[members.0x30]
name = "dwSupport"
offset = 0x30
type = "DWORD"
size = 0x4
