last_change = 2026-06-27T20:49:16.897728Z
name = "tagMSGBOXPARAMSA"
size = 0x28

[members.0x0]
name = "cbSize"
offset = 0x0
type = "UINT"
size = 0x4

[members.0x4]
name = "hwndOwner"
offset = 0x4
type = "HWND"
size = 0x4

[members.0x8]
name = "hInstance"
offset = 0x8
type = "HINSTANCE"
size = 0x4

[members.0xc]
name = "lpszText"
offset = 0xc
type = "LPCSTR"
size = 0x4

[members.0x10]
name = "lpszCaption"
offset = 0x10
type = "LPCSTR"
size = 0x4

[members.0x14]
name = "dwStyle"
offset = 0x14
type = "DWORD"
size = 0x4

[members.0x18]
name = "lpszIcon"
offset = 0x18
type = "LPCSTR"
size = 0x4

[members.0x1c]
name = "dwContextHelpId"
offset = 0x1c
type = "DWORD_PTR"
size = 0x4

[members.0x20]
name = "lpfnMsgBoxCallback"
offset = 0x20
type = "MSGBOXCALLBACK"
size = 0x4

[members.0x24]
name = "dwLanguageId"
offset = 0x24
type = "DWORD"
size = 0x4
