last_change = 2026-06-27T20:49:16.895640Z
name = "tagMONERRSTRUCT"
size = 0x10

[members.0x0]
name = "cb"
offset = 0x0
type = "UINT"
size = 0x4

[members.0x4]
name = "wLastError"
offset = 0x4
type = "UINT"
size = 0x4

[members.0x8]
name = "dwTime"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "hTask"
offset = 0xc
type = "HANDLE"
size = 0x4
