last_change = 2026-06-27T20:49:16.888210Z
name = "tagMCI_STATUS_PARMS"
size = 0x10

[members.0x0]
name = "dwCallback"
offset = 0x0
type = "DWORD_PTR"
size = 0x4

[members.0x4]
name = "dwReturn"
offset = 0x4
type = "DWORD_PTR"
size = 0x4

[members.0x8]
name = "dwItem"
offset = 0x8
type = "DWORD"
size = 0x4

[members.0xc]
name = "dwTrack"
offset = 0xc
type = "DWORD"
size = 0x4
