last_change = 2026-06-27T20:49:16.915773Z
name = "tagServerInformation"
size = 0x10

[members.0x0]
name = "dwServerPid"
offset = 0x0
type = "DWORD"
size = 0x4

[members.0x4]
name = "dwServerTid"
offset = 0x4
type = "DWORD"
size = 0x4

[members.0x8]
name = "ui64ServerAddress"
offset = 0x8
type = "UINT64"
size = 0x8
