last_change = 2026-06-27T20:49:16.921290Z
name = "tagWAVEOUTCAPSW"
size = 0x54

[members.0x0]
name = "wMid"
offset = 0x0
type = "WORD"
size = 0x2

[members.0x2]
name = "wPid"
offset = 0x2
type = "WORD"
size = 0x2

[members.0x4]
name = "vDriverVersion"
offset = 0x4
type = "MMVERSION"
size = 0x4

[members.0x8]
name = "szPname"
offset = 0x8
type = "WCHAR[0x20]"
size = 0x40

[members.0x48]
name = "dwFormats"
offset = 0x48
type = "DWORD"
size = 0x4

[members.0x4c]
name = "wChannels"
offset = 0x4c
type = "WORD"
size = 0x2

[members.0x4e]
name = "wReserved1"
offset = 0x4e
type = "WORD"
size = 0x2

[members.0x50]
name = "dwSupport"
offset = 0x50
type = "DWORD"
size = 0x4
